# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import manifest_pb2 as proto_dot_manifest__pb2


class ArchitectBrainStub(object):
    """The actual service the Python Brain will run
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RefineManifest = channel.unary_unary(
                '/archon.manifest.v1.ArchitectBrain/RefineManifest',
                request_serializer=proto_dot_manifest__pb2.RefineManifestRequest.SerializeToString,
                response_deserializer=proto_dot_manifest__pb2.RefineManifestResponse.FromString,
                )


class ArchitectBrainServicer(object):
    """The actual service the Python Brain will run
    """

    def RefineManifest(self, request, context):
        """Sync call: Quickly updates the manifest based on user chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchitectBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RefineManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.RefineManifest,
                    request_deserializer=proto_dot_manifest__pb2.RefineManifestRequest.FromString,
                    response_serializer=proto_dot_manifest__pb2.RefineManifestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'archon.manifest.v1.ArchitectBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArchitectBrain(object):
    """The actual service the Python Brain will run
    """

    @staticmethod
    def RefineManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/archon.manifest.v1.ArchitectBrain/RefineManifest',
            proto_dot_manifest__pb2.RefineManifestRequest.SerializeToString,
            proto_dot_manifest__pb2.RefineManifestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
