// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/manifest.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArchitectBrain_RefineManifest_FullMethodName = "/archon.manifest.v1.ArchitectBrain/RefineManifest"
)

// ArchitectBrainClient is the client API for ArchitectBrain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The actual service the Python Brain will run
type ArchitectBrainClient interface {
	// Sync call: Quickly updates the manifest based on user chat
	RefineManifest(ctx context.Context, in *RefineManifestRequest, opts ...grpc.CallOption) (*RefineManifestResponse, error)
}

type architectBrainClient struct {
	cc grpc.ClientConnInterface
}

func NewArchitectBrainClient(cc grpc.ClientConnInterface) ArchitectBrainClient {
	return &architectBrainClient{cc}
}

func (c *architectBrainClient) RefineManifest(ctx context.Context, in *RefineManifestRequest, opts ...grpc.CallOption) (*RefineManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefineManifestResponse)
	err := c.cc.Invoke(ctx, ArchitectBrain_RefineManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchitectBrainServer is the server API for ArchitectBrain service.
// All implementations must embed UnimplementedArchitectBrainServer
// for forward compatibility.
//
// The actual service the Python Brain will run
type ArchitectBrainServer interface {
	// Sync call: Quickly updates the manifest based on user chat
	RefineManifest(context.Context, *RefineManifestRequest) (*RefineManifestResponse, error)
	mustEmbedUnimplementedArchitectBrainServer()
}

// UnimplementedArchitectBrainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchitectBrainServer struct{}

func (UnimplementedArchitectBrainServer) RefineManifest(context.Context, *RefineManifestRequest) (*RefineManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefineManifest not implemented")
}
func (UnimplementedArchitectBrainServer) mustEmbedUnimplementedArchitectBrainServer() {}
func (UnimplementedArchitectBrainServer) testEmbeddedByValue()                        {}

// UnsafeArchitectBrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchitectBrainServer will
// result in compilation errors.
type UnsafeArchitectBrainServer interface {
	mustEmbedUnimplementedArchitectBrainServer()
}

func RegisterArchitectBrainServer(s grpc.ServiceRegistrar, srv ArchitectBrainServer) {
	// If the following call panics, it indicates UnimplementedArchitectBrainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchitectBrain_ServiceDesc, srv)
}

func _ArchitectBrain_RefineManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchitectBrainServer).RefineManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchitectBrain_RefineManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchitectBrainServer).RefineManifest(ctx, req.(*RefineManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchitectBrain_ServiceDesc is the grpc.ServiceDesc for ArchitectBrain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchitectBrain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archon.manifest.v1.ArchitectBrain",
	HandlerType: (*ArchitectBrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefineManifest",
			Handler:    _ArchitectBrain_RefineManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/manifest.proto",
}
