// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/manifest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	TargetCloud   string                 `protobuf:"bytes,2,opt,name=target_cloud,json=targetCloud,proto3" json:"target_cloud,omitempty"`       // e.g., "AWS", "Vercel", "GCP"
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Crucial for backwards compatibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Metadata) GetTargetCloud() string {
	if x != nil {
		return x.TargetCloud
	}
	return ""
}

func (x *Metadata) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type ArchitectureNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // e.g., "auth_service"
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                               // e.g., "clerk", "postgres", "redis"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                         // e.g., "1.2.0"
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for env vars or settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchitectureNode) Reset() {
	*x = ArchitectureNode{}
	mi := &file_proto_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchitectureNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchitectureNode) ProtoMessage() {}

func (x *ArchitectureNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchitectureNode.ProtoReflect.Descriptor instead.
func (*ArchitectureNode) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ArchitectureNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArchitectureNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArchitectureNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ArchitectureNode) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // e.g., "api_gateway"
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // e.g., "postgres_db"
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                 // e.g., "gRPC", "TCP", "HTTP"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_proto_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *Connection) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Connection) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Connection) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// The Main Source of Truth
type ProjectManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Nodes         []*ArchitectureNode    `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Connections   []*Connection          `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	FeatureFlags  []string               `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectManifest) Reset() {
	*x = ProjectManifest{}
	mi := &file_proto_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectManifest) ProtoMessage() {}

func (x *ProjectManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectManifest.ProtoReflect.Descriptor instead.
func (*ProjectManifest) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectManifest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProjectManifest) GetNodes() []*ArchitectureNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ProjectManifest) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *ProjectManifest) GetFeatureFlags() []string {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

// The request sent from the Go Gateway -> Python AI Brain
type RefineManifestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`          // For OpenTelemetry tracking
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // For Auth/Audit logging
	UserPrompt      string                 `protobuf:"bytes,3,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"` // e.g., "Swap my DB to MongoDB"
	CurrentManifest *ProjectManifest       `protobuf:"bytes,4,opt,name=current_manifest,json=currentManifest,proto3" json:"current_manifest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefineManifestRequest) Reset() {
	*x = RefineManifestRequest{}
	mi := &file_proto_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineManifestRequest) ProtoMessage() {}

func (x *RefineManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineManifestRequest.ProtoReflect.Descriptor instead.
func (*RefineManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *RefineManifestRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RefineManifestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefineManifestRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *RefineManifestRequest) GetCurrentManifest() *ProjectManifest {
	if x != nil {
		return x.CurrentManifest
	}
	return nil
}

// The response sent from Python AI Brain -> Go Gateway
type RefineManifestResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	IsValid         bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	AiReasoning     string                 `protobuf:"bytes,3,opt,name=ai_reasoning,json=aiReasoning,proto3" json:"ai_reasoning,omitempty"` // Explanation to show on the UI
	UpdatedManifest *ProjectManifest       `protobuf:"bytes,4,opt,name=updated_manifest,json=updatedManifest,proto3" json:"updated_manifest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefineManifestResponse) Reset() {
	*x = RefineManifestResponse{}
	mi := &file_proto_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineManifestResponse) ProtoMessage() {}

func (x *RefineManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineManifestResponse.ProtoReflect.Descriptor instead.
func (*RefineManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *RefineManifestResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RefineManifestResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *RefineManifestResponse) GetAiReasoning() string {
	if x != nil {
		return x.AiReasoning
	}
	return ""
}

func (x *RefineManifestResponse) GetUpdatedManifest() *ProjectManifest {
	if x != nil {
		return x.UpdatedManifest
	}
	return nil
}

var File_proto_manifest_proto protoreflect.FileDescriptor

const file_proto_manifest_proto_rawDesc = "" +
	"\n" +
	"\x14proto/manifest.proto\x12\x12archon.manifest.v1\"w\n" +
	"\bMetadata\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12!\n" +
	"\ftarget_cloud\x18\x02 \x01(\tR\vtargetCloud\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\"\xd5\x01\n" +
	"\x10ArchitectureNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12H\n" +
	"\x06config\x18\x04 \x03(\v20.archon.manifest.v1.ArchitectureNode.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xee\x01\n" +
	"\x0fProjectManifest\x128\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1c.archon.manifest.v1.MetadataR\bmetadata\x12:\n" +
	"\x05nodes\x18\x02 \x03(\v2$.archon.manifest.v1.ArchitectureNodeR\x05nodes\x12@\n" +
	"\vconnections\x18\x03 \x03(\v2\x1e.archon.manifest.v1.ConnectionR\vconnections\x12#\n" +
	"\rfeature_flags\x18\x04 \x03(\tR\ffeatureFlags\"\xbc\x01\n" +
	"\x15RefineManifestRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vuser_prompt\x18\x03 \x01(\tR\n" +
	"userPrompt\x12N\n" +
	"\x10current_manifest\x18\x04 \x01(\v2#.archon.manifest.v1.ProjectManifestR\x0fcurrentManifest\"\xc1\x01\n" +
	"\x16RefineManifestResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\x12!\n" +
	"\fai_reasoning\x18\x03 \x01(\tR\vaiReasoning\x12N\n" +
	"\x10updated_manifest\x18\x04 \x01(\v2#.archon.manifest.v1.ProjectManifestR\x0fupdatedManifest2y\n" +
	"\x0eArchitectBrain\x12g\n" +
	"\x0eRefineManifest\x12).archon.manifest.v1.RefineManifestRequest\x1a*.archon.manifest.v1.RefineManifestResponseB%Z#github.com/kisna/archon/internal/pbb\x06proto3"

var (
	file_proto_manifest_proto_rawDescOnce sync.Once
	file_proto_manifest_proto_rawDescData []byte
)

func file_proto_manifest_proto_rawDescGZIP() []byte {
	file_proto_manifest_proto_rawDescOnce.Do(func() {
		file_proto_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manifest_proto_rawDesc), len(file_proto_manifest_proto_rawDesc)))
	})
	return file_proto_manifest_proto_rawDescData
}

var file_proto_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_manifest_proto_goTypes = []any{
	(*Metadata)(nil),               // 0: archon.manifest.v1.Metadata
	(*ArchitectureNode)(nil),       // 1: archon.manifest.v1.ArchitectureNode
	(*Connection)(nil),             // 2: archon.manifest.v1.Connection
	(*ProjectManifest)(nil),        // 3: archon.manifest.v1.ProjectManifest
	(*RefineManifestRequest)(nil),  // 4: archon.manifest.v1.RefineManifestRequest
	(*RefineManifestResponse)(nil), // 5: archon.manifest.v1.RefineManifestResponse
	nil,                            // 6: archon.manifest.v1.ArchitectureNode.ConfigEntry
}
var file_proto_manifest_proto_depIdxs = []int32{
	6, // 0: archon.manifest.v1.ArchitectureNode.config:type_name -> archon.manifest.v1.ArchitectureNode.ConfigEntry
	0, // 1: archon.manifest.v1.ProjectManifest.metadata:type_name -> archon.manifest.v1.Metadata
	1, // 2: archon.manifest.v1.ProjectManifest.nodes:type_name -> archon.manifest.v1.ArchitectureNode
	2, // 3: archon.manifest.v1.ProjectManifest.connections:type_name -> archon.manifest.v1.Connection
	3, // 4: archon.manifest.v1.RefineManifestRequest.current_manifest:type_name -> archon.manifest.v1.ProjectManifest
	3, // 5: archon.manifest.v1.RefineManifestResponse.updated_manifest:type_name -> archon.manifest.v1.ProjectManifest
	4, // 6: archon.manifest.v1.ArchitectBrain.RefineManifest:input_type -> archon.manifest.v1.RefineManifestRequest
	5, // 7: archon.manifest.v1.ArchitectBrain.RefineManifest:output_type -> archon.manifest.v1.RefineManifestResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_manifest_proto_init() }
func file_proto_manifest_proto_init() {
	if File_proto_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manifest_proto_rawDesc), len(file_proto_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manifest_proto_goTypes,
		DependencyIndexes: file_proto_manifest_proto_depIdxs,
		MessageInfos:      file_proto_manifest_proto_msgTypes,
	}.Build()
	File_proto_manifest_proto = out.File
	file_proto_manifest_proto_goTypes = nil
	file_proto_manifest_proto_depIdxs = nil
}
