# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manifest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emanifest.proto\x12\x12\x61rchon.manifest.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n\x08Metadata\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\x12\x14\n\x0ctarget_cloud\x18\x02 \x01(\t\x12\x16\n\x0eschema_version\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"f\n\x10\x41rchitectureNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\'\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"D\n\nConnection\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\"\xc2\x01\n\x0fProjectManifest\x12.\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.archon.manifest.v1.Metadata\x12\x33\n\x05nodes\x18\x02 \x03(\x0b\x32$.archon.manifest.v1.ArchitectureNode\x12\x33\n\x0b\x63onnections\x18\x03 \x03(\x0b\x32\x1e.archon.manifest.v1.Connection\x12\x15\n\rfeature_flags\x18\x04 \x03(\t\"\xa2\x01\n\x15RefineManifestRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0buser_prompt\x18\x03 \x01(\t\x12=\n\x10\x63urrent_manifest\x18\x04 \x01(\x0b\x32#.archon.manifest.v1.ProjectManifest\x12\x12\n\nproject_id\x18\x05 \x01(\t\"\x91\x01\n\x16RefineManifestResponse\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x14\n\x0c\x61i_reasoning\x18\x03 \x01(\t\x12=\n\x10updated_manifest\x18\x04 \x01(\x0b\x32#.archon.manifest.v1.ProjectManifest2y\n\x0e\x41rchitectBrain\x12g\n\x0eRefineManifest\x12).archon.manifest.v1.RefineManifestRequest\x1a*.archon.manifest.v1.RefineManifestResponseB%Z#github.com/kisna/archon/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/kisna/archon/internal/pb'
  _globals['_METADATA']._serialized_start=101
  _globals['_METADATA']._serialized_end=227
  _globals['_ARCHITECTURENODE']._serialized_start=229
  _globals['_ARCHITECTURENODE']._serialized_end=331
  _globals['_CONNECTION']._serialized_start=333
  _globals['_CONNECTION']._serialized_end=401
  _globals['_PROJECTMANIFEST']._serialized_start=404
  _globals['_PROJECTMANIFEST']._serialized_end=598
  _globals['_REFINEMANIFESTREQUEST']._serialized_start=601
  _globals['_REFINEMANIFESTREQUEST']._serialized_end=763
  _globals['_REFINEMANIFESTRESPONSE']._serialized_start=766
  _globals['_REFINEMANIFESTRESPONSE']._serialized_end=911
  _globals['_ARCHITECTBRAIN']._serialized_start=913
  _globals['_ARCHITECTBRAIN']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
