// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type ManifestRecord struct {
	ID           string `json:"id"`
	ProjectID    string `json:"projectId"`
	VersionHash  string `json:"versionHash"`
	ManifestData string `json:"manifestData"`
}

type Mutation struct {
}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}

type RefineResponse struct {
	IsValid   bool            `json:"isValid"`
	Reasoning string          `json:"reasoning"`
	Manifest  *ManifestRecord `json:"manifest,omitempty"`
}
