package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/kisna/archon/internal/kafka"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string) (*Project, error) {
	// Hardcoding the dummy user ID we put in our init.sql for now
	userID := uuid.MustParse("11111111-1111-1111-1111-111111111111")

	p, err := r.DB.CreateProject(ctx, userID, name)
	if err != nil {
		return nil, err
	}

	// Create an empty manifest for the new project
	emptyManifest := []byte(`{"metadata": {"project_name": "` + name + `"}, "nodes": [], "connections": []}`)
	err = r.DB.SaveManifest(ctx, p.ID, "init-hash", emptyManifest)
	if err != nil {
		return nil, err
	}

	return &Project{ID: p.ID.String(), Name: p.Name}, nil
}

// RefineArchitecture is the magic resolver that talks to the AI
func (r *mutationResolver) RefineArchitecture(ctx context.Context, projectID string, prompt string) (*RefineResponse, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}

	// 1. Fetch current architecture from DB
	currentManifest, err := r.DB.GetLatestManifest(ctx, pID)
	var currentData []byte
	if err == nil && currentManifest != nil {
		currentData = currentManifest.ManifestData
	}

	// 2. Call the AI Brain via gRPC! (Passing dummy trace/user IDs for now)
	newData, reasoning, err := r.AI.Refine(ctx, "trace-123", "user-123", prompt, currentData)

	if err != nil {
		// AI Rejected it (e.g., "Invalid architecture request")
		return &RefineResponse{
			IsValid:   false,
			Reasoning: reasoning,
			Manifest:  nil,
		}, nil
	}

	// 3. AI Approved it! Hash the new JSON and save it as a new version.
	hash := sha256.Sum256(newData)
	versionHash := hex.EncodeToString(hash[:])

	err = r.DB.SaveManifest(ctx, pID, versionHash, newData)
	if err != nil {
		return nil, fmt.Errorf("failed to save new manifest: %w", err)
	}

	return &RefineResponse{
		IsValid:   true,
		Reasoning: reasoning,
		Manifest: &ManifestRecord{
			ID:           "latest", // simplified for frontend
			ProjectID:    projectID,
			VersionHash:  versionHash,
			ManifestData: string(newData),
		},
	}, nil
}

// ShipProject is the resolver for the shipProject field.
// ShipProject is the resolver for the shipProject field.
func (r *mutationResolver) ShipProject(ctx context.Context, projectID string) (bool, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return false, fmt.Errorf("invalid project ID")
	}

	// 1. Get the latest approved architecture from the DB
	manifest, err := r.DB.GetLatestManifest(ctx, pID)
	if err != nil {
		return false, fmt.Errorf("could not find architecture to build: %w", err)
	}

	// 2. Build the Event Payload
	event := kafka.BuildRequestedEvent{
		ProjectID:   projectID,
		VersionHash: manifest.VersionHash,
		ManifestRaw: string(manifest.ManifestData),
		RequestedAt: time.Now(),
	}

	// 3. Drop it into Kafka!
	err = r.Kafka.PublishBuildRequest(ctx, event)
	if err != nil {
		return false, fmt.Errorf("failed to trigger build pipeline: %w", err)
	}

	return true, nil
}

// GetLatestManifest is the resolver for the getLatestManifest field.
func (r *queryResolver) GetLatestManifest(ctx context.Context, projectID string) (*ManifestRecord, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}

	m, err := r.DB.GetLatestManifest(ctx, pID)
	if err != nil {
		return nil, fmt.Errorf("manifest not found")
	}

	return &ManifestRecord{
		ID:           m.ID.String(),
		ProjectID:    m.ProjectID.String(),
		VersionHash:  m.VersionHash,
		ManifestData: string(m.ManifestData),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) ShipProject(ctx context.Context, projectID string) (bool, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return false, fmt.Errorf("invalid project ID")
	}

	// 1. Get the latest approved architecture from the DB
	manifest, err := r.DB.GetLatestManifest(ctx, pID)
	if err != nil {
		return false, fmt.Errorf("could not find architecture to build: %w", err)
	}

	// 2. Build the Event Payload
	event := kafka.BuildRequestedEvent{
		ProjectID:   projectID,
		VersionHash: manifest.VersionHash,
		ManifestRaw: string(manifest.ManifestData),
		RequestedAt: time.Now(),
	}

	// 3. Drop it into Kafka!
	err = r.Kafka.PublishBuildRequest(ctx, event)
	if err != nil {
		return false, fmt.Errorf("failed to trigger build pipeline: %w", err)
	}

	return true, nil
}
*/
