package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/kisna/archon/services/api-gateway/internal/kafka"
	"github.com/kisna/archon/internal/pb"
	"google.golang.org/protobuf/encoding/protojson"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string) (*Project, error) {
	// Hardcoding the dummy user ID we put in our init.sql for now
	userID := uuid.MustParse("11111111-1111-1111-1111-111111111111")

	// Create an empty manifest string
	emptyManifest := []byte(`{"metadata": {"project_name": "` + name + `"}, "nodes": [], "connections": []}`)
	
	// FIX: Use the new atomic transaction method!
	p, err := r.DB.CreateProjectWithManifest(ctx, userID, name, emptyManifest)
	if err != nil {
		return nil, err
	}

	return &Project{ID: p.ID.String(), Name: p.Name}, nil
}

// RefineArchitecture is the magic resolver that talks to the AI
func (r *mutationResolver) RefineArchitecture(ctx context.Context, projectID string, prompt string) (*RefineResponse, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}

	// 1. Fetch current architecture from DB
	currentManifest, err := r.DB.GetLatestManifest(ctx, pID)
	var currentData []byte
	if err == nil && currentManifest != nil {
		currentData = currentManifest.ManifestData
	}

	// 2. Build the Protobuf Request Payload
	currentPb := &pb.ProjectManifest{}
	if len(currentData) > 0 {
		if err := protojson.Unmarshal(currentData, currentPb); err != nil {
			return nil, fmt.Errorf("failed to parse current architecture: %w", err)
		}
	}

	req := &pb.RefineManifestRequest{
		TraceId:         uuid.New().String(),
		UserId:          "11111111-1111-1111-1111-111111111111", // Dummy user for now
		CurrentManifest: currentPb,
		UserPrompt:      prompt,
	}

	// 3. Call the AI Brain via gRPC!
	// Add a strict 60-second timeout to the AI call
	aiCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	resp, err := r.AI.Refine(aiCtx, req)
	if err != nil {
		// Path A: The system failed (timeout, network drop, AI Brain crashed)
		fmt.Printf("❌ [INTERNAL ERROR] AI gRPC Call Failed: %v\n", err)
		return nil, fmt.Errorf("the AI architect service is currently unavailable, please try again later")
	}

	if !resp.IsValid {
		// Path B: The system succeeded, but the AI actively rejected the user's prompt
		return &RefineResponse{
			IsValid:   false,
			Reasoning: resp.AiReasoning,
		}, nil
	}

	// Path C: The AI approved the change and returned new JSON.
	newData, err := protojson.Marshal(resp.UpdatedManifest)
	if err != nil {
		return nil, fmt.Errorf("failed to parse AI response: %w", err)
	}

	// 4. AI Approved it! Hash the new JSON and save it as a new version.
	hash := sha256.Sum256(newData)
	versionHash := hex.EncodeToString(hash[:])

	err = r.DB.SaveManifest(ctx, pID, versionHash, newData)
	if err != nil {
		return nil, fmt.Errorf("failed to save new manifest: %w", err)
	}

	// 5. Broadcast the update to all connected WebSockets via Redis!
	go func(project string, data string) {
		// 1. Catch panics so the Gateway doesn't crash
		defer func() {
			if r := recover(); r != nil {
				fmt.Printf("⚠️ [PANIC RECOVERED] Redis Broadcast Panic: %v\n", r)
			}
		}()

		// 2. Give the background task its own bounded context 
		// (Don't use the HTTP request context as it cancels when the HTTP request ends)
		bgCtx, bgCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer bgCancel()

		pubErr := r.Redis.PublishManifestUpdate(bgCtx, project, data)
		if pubErr != nil {
			fmt.Printf("⚠️ Redis Publish Error: %v\n", pubErr)
		}
	}(projectID, string(newData))

	return &RefineResponse{
		IsValid:   true,
		Reasoning: resp.AiReasoning, // FIXED: Using the AI's returned reasoning
		Manifest: &ManifestRecord{
			ID:           "latest",
			ProjectID:    projectID,
			VersionHash:  versionHash,
			ManifestData: string(newData),
		},
	}, nil
}

// ShipProject is the resolver for the shipProject field.
func (r *mutationResolver) ShipProject(ctx context.Context, projectID string) (bool, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return false, fmt.Errorf("invalid project ID")
	}

	// 1. Get the latest approved architecture from the DB
	manifest, err := r.DB.GetLatestManifest(ctx, pID)
	if err != nil {
		return false, fmt.Errorf("could not find architecture to build: %w", err)
	}

	// 2. Build the Event Payload
	event := kafka.BuildRequestedEvent{
		ProjectID:   projectID,
		VersionHash: manifest.VersionHash,
		ManifestRaw: string(manifest.ManifestData),
		RequestedAt: time.Now(),
	}

	// 3. Drop it into Kafka!
	err = r.Kafka.PublishBuildRequest(ctx, event)
	if err != nil {
		return false, fmt.Errorf("failed to trigger build pipeline: %w", err)
	}

	return true, nil
}

// GetLatestManifest is the resolver for the getLatestManifest field.
func (r *queryResolver) GetLatestManifest(ctx context.Context, projectID string) (*ManifestRecord, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}

	m, err := r.DB.GetLatestManifest(ctx, pID)
	if err != nil {
		return nil, fmt.Errorf("failed to query manifest: %w", err)
	}

	// PROD FIX: Safely handle the case where the project exists but has no manifest yet
	if m == nil {
		return nil, nil 
	}

	return &ManifestRecord{
		ID:           m.ID.String(),
		ProjectID:    m.ProjectID.String(),
		VersionHash:  m.VersionHash,
		ManifestData: string(m.ManifestData),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }