package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repository provides access to the database using type-safe sqlc queries.
type Repository struct {
	Pool    *pgxpool.Pool
	Queries *Queries // Generated by sqlc
}

// NewRepository creates a new db repository.
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{
		Pool:    pool,
		Queries: New(pool),
	}
}

func (r *Repository) CreateProject(ctx context.Context, userID uuid.UUID, name string) (*Project, error) {
	p, err := r.Queries.CreateProject(ctx, CreateProjectParams{
		UserID: userID,
		Name:   name,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create project: %w", err)
	}
	return &p, nil
}

func (r *Repository) SaveManifest(ctx context.Context, projectID uuid.UUID, versionHash string, manifestData []byte) error {
	return r.Queries.SaveManifest(ctx, SaveManifestParams{
		ProjectID:    projectID,
		VersionHash:  versionHash,
		ManifestData: manifestData,
	})
}

func (r *Repository) GetLatestManifest(ctx context.Context, projectID uuid.UUID) (*Manifest, error) {
	m, err := r.Queries.GetLatestManifest(ctx, projectID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil // Valid state for new projects
		}
		return nil, fmt.Errorf("querying latest manifest: %w", err)
	}
	return &m, nil
}

// CreateProjectWithManifest uses sqlc's WithTx to execute safely within a transaction
func (r *Repository) CreateProjectWithManifest(ctx context.Context, userID uuid.UUID, name string, manifestData []byte) (*Project, error) {
	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	qtx := r.Queries.WithTx(tx)

	p, err := qtx.CreateProject(ctx, CreateProjectParams{
		UserID: userID,
		Name:   name,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to insert project: %w", err)
	}

	err = qtx.SaveManifest(ctx, SaveManifestParams{
		ProjectID:    p.ID,
		VersionHash:  "init-hash",
		ManifestData: manifestData,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to insert initial manifest: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &p, nil
}