# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emanifest.proto\x12\x12\x61rchon.manifest.v1\"N\n\x08Metadata\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\x12\x14\n\x0ctarget_cloud\x18\x02 \x01(\t\x12\x16\n\x0eschema_version\x18\x03 \x01(\t\"\xae\x01\n\x10\x41rchitectureNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12@\n\x06\x63onfig\x18\x04 \x03(\x0b\x32\x30.archon.manifest.v1.ArchitectureNode.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\nConnection\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\"\xc2\x01\n\x0fProjectManifest\x12.\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.archon.manifest.v1.Metadata\x12\x33\n\x05nodes\x18\x02 \x03(\x0b\x32$.archon.manifest.v1.ArchitectureNode\x12\x33\n\x0b\x63onnections\x18\x03 \x03(\x0b\x32\x1e.archon.manifest.v1.Connection\x12\x15\n\rfeature_flags\x18\x04 \x03(\t\"\x8e\x01\n\x15RefineManifestRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0buser_prompt\x18\x03 \x01(\t\x12=\n\x10\x63urrent_manifest\x18\x04 \x01(\x0b\x32#.archon.manifest.v1.ProjectManifest\"\x91\x01\n\x16RefineManifestResponse\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x14\n\x0c\x61i_reasoning\x18\x03 \x01(\t\x12=\n\x10updated_manifest\x18\x04 \x01(\x0b\x32#.archon.manifest.v1.ProjectManifest2y\n\x0e\x41rchitectBrain\x12g\n\x0eRefineManifest\x12).archon.manifest.v1.RefineManifestRequest\x1a*.archon.manifest.v1.RefineManifestResponseB%Z#github.com/kisna/archon/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/kisna/archon/internal/pb'
  _globals['_ARCHITECTURENODE_CONFIGENTRY']._loaded_options = None
  _globals['_ARCHITECTURENODE_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_METADATA']._serialized_start=38
  _globals['_METADATA']._serialized_end=116
  _globals['_ARCHITECTURENODE']._serialized_start=119
  _globals['_ARCHITECTURENODE']._serialized_end=293
  _globals['_ARCHITECTURENODE_CONFIGENTRY']._serialized_start=248
  _globals['_ARCHITECTURENODE_CONFIGENTRY']._serialized_end=293
  _globals['_CONNECTION']._serialized_start=295
  _globals['_CONNECTION']._serialized_end=363
  _globals['_PROJECTMANIFEST']._serialized_start=366
  _globals['_PROJECTMANIFEST']._serialized_end=560
  _globals['_REFINEMANIFESTREQUEST']._serialized_start=563
  _globals['_REFINEMANIFESTREQUEST']._serialized_end=705
  _globals['_REFINEMANIFESTRESPONSE']._serialized_start=708
  _globals['_REFINEMANIFESTRESPONSE']._serialized_end=853
  _globals['_ARCHITECTBRAIN']._serialized_start=855
  _globals['_ARCHITECTBRAIN']._serialized_end=976
# @@protoc_insertion_point(module_scope)
